### Creating a function that pulls data from a companyâ€™s income statement

In [1]:
import pandas as pd
import requests
from dotenv import load_dotenv
import os
load_dotenv()
api_key = os.getenv("FINANCIAL_API_KEY")
#Function that returns income statement data
def get_data2(stock):
    data = requests.get(f"https://financialmodelingprep.com/api/v3/income-statement/{stock}?period=quarter&limit=400&apikey={api_key}")

    data = data.json()
# Pull data from the previous four quarters. The 0 refers to the most previous quarter etc. 
    data = data[0:5]
    
    return data

In [2]:
get_data2("PRI")

[{'date': '2020-09-30',
  'symbol': 'PRI',
  'fillingDate': '2020-11-05',
  'acceptedDate': '2020-11-05 16:43:17',
  'period': 'Q3',
  'revenue': 568461000,
  'costOfRevenue': 0.0,
  'grossProfit': 568461000,
  'grossProfitRatio': 1.0,
  'researchAndDevelopmentExpenses': 0.0,
  'generalAndAdministrativeExpenses': 0.0,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 59347000,
  'operatingExpenses': 59347000,
  'costAndExpenses': 59347000,
  'interestExpense': 14704000,
  'depreciationAndAmortization': 47491000,
  'ebitda': 193974000,
  'ebitdaratio': 0.3412265749101521,
  'operatingIncome': 146483000,
  'operatingIncomeRatio': 0.25768346465280817,
  'totalOtherIncomeExpensesNet': 0.0,
  'incomeBeforeTax': 146483000,
  'incomeBeforeTaxRatio': 0.25768346465280817,
  'incomeTaxExpense': 0.0,
  'netIncome': 112101000,
  'netIncomeRatio': 0.19720086338376774,
  'eps': 2.82,
  'epsdiluted': 2.81,
  'weightedAverageShsOut': 39588000,
  'weightedAverageShsOutDil': 39710000,
  'link': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020051406/0001564590-20-051406-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020051406/pri-10q_20200930.htm'},
 {'date': '2020-06-30',
  'symbol': 'PRI',
  'fillingDate': '2020-08-06',
  'acceptedDate': '2020-08-06 14:25:32',
  'period': 'Q2',
  'revenue': 501363000,
  'costOfRevenue': 0.0,
  'grossProfit': 501363000,
  'grossProfitRatio': 1.0,
  'researchAndDevelopmentExpenses': 0.0,
  'generalAndAdministrativeExpenses': 85492000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 56152000,
  'operatingExpenses': 385098000,
  'costAndExpenses': 385098000,
  'interestExpense': 7200000.0,
  'depreciationAndAmortization': 57055999.99999999,
  'ebitda': 198318000,
  'ebitdaratio': 0.395558,
  'operatingIncome': 141262000,
  'operatingIncomeRatio': 0.281756,
  'totalOtherIncomeExpensesNet': 0.0,
  'incomeBeforeTax': 134062000,
  'incomeBeforeTaxRatio': 0.267395,
  'incomeTaxExpense': 32552000,
  'netIncome': 101510000,
  'netIncomeRatio': 0.202468,
  'eps': 2.52224,
  'epsdiluted': 2.52224,
  'weightedAverageShsOut': 40246000,
  'weightedAverageShsOutDil': 40246000,
  'link': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020037582/0001564590-20-037582-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020037582/pri-10q_20200630.htm'},
 {'date': '2020-03-31',
  'symbol': 'PRI',
  'fillingDate': '2020-05-01',
  'acceptedDate': '2020-05-01 11:20:29',
  'period': 'Q1',
  'revenue': 519546000,
  'costOfRevenue': 0.0,
  'grossProfit': 519546000,
  'grossProfitRatio': 1.0,
  'researchAndDevelopmentExpenses': 0.0,
  'generalAndAdministrativeExpenses': 96607000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 65914000,
  'operatingExpenses': 426899000,
  'costAndExpenses': 426899000,
  'interestExpense': 7192000.0,
  'depreciationAndAmortization': 74251000,
  'ebitda': 175989000,
  'ebitdaratio': 0.338736,
  'operatingIncome': 101738000,
  'operatingIncomeRatio': 0.195821,
  'totalOtherIncomeExpensesNet': 0.0,
  'incomeBeforeTax': 94546000,
  'incomeBeforeTaxRatio': 0.181978,
  'incomeTaxExpense': 22077000,
  'netIncome': 72469000,
  'netIncomeRatio': 0.139485,
  'eps': 1.75729,
  'epsdiluted': 1.75729,
  'weightedAverageShsOut': 41239000,
  'weightedAverageShsOutDil': 41239000,
  'link': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020020401/0001564590-20-020401-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020007489/pri-10k_20191231.htm'},
 {'date': '2019-12-31',
  'symbol': 'PRI',
  'fillingDate': '2020-02-28',
  'acceptedDate': '2020-02-27 18:00:34',
  'period': 'Q4',
  'revenue': 508776000,
  'costOfRevenue': 0.0,
  'grossProfit': 508776000,
  'grossProfitRatio': 1.0,
  'researchAndDevelopmentExpenses': 0.0,
  'generalAndAdministrativeExpenses': 94238000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 60676000,
  'operatingExpenses': 402701000,
  'costAndExpenses': 402701000,
  'interestExpense': 7222000.0,
  'depreciationAndAmortization': 72294000,
  'ebitda': 201660000,
  'ebitdaratio': 0.396363,
  'operatingIncome': 129366000,
  'operatingIncomeRatio': 0.254269,
  'totalOtherIncomeExpensesNet': 0.0,
  'incomeBeforeTax': 122144000,
  'incomeBeforeTaxRatio': 0.240074,
  'incomeTaxExpense': 28587000,
  'netIncome': 93557000,
  'netIncomeRatio': 0.183886,
  'eps': 2.24864,
  'epsdiluted': 2.24864,
  'weightedAverageShsOut': 41606000,
  'weightedAverageShsOutDil': 41606000,
  'link': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020007489/0001564590-20-007489-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459020007489/pri-10k_20191231.htm'},
 {'date': '2019-09-30',
  'symbol': 'PRI',
  'fillingDate': '2019-11-07',
  'acceptedDate': '2019-11-07 15:17:19',
  'period': 'Q3',
  'revenue': 497693000,
  'costOfRevenue': 0.0,
  'grossProfit': 497693000,
  'grossProfitRatio': 1.0,
  'researchAndDevelopmentExpenses': 0.0,
  'generalAndAdministrativeExpenses': 89061000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 54843000,
  'operatingExpenses': 389369000,
  'costAndExpenses': 389369000,
  'interestExpense': 7208000.0,
  'depreciationAndAmortization': 68678000,
  'ebitda': 201025000,
  'ebitdaratio': 0.403914,
  'operatingIncome': 132348000,
  'operatingIncomeRatio': 0.265923,
  'totalOtherIncomeExpensesNet': 0.0,
  'incomeBeforeTax': 125139000,
  'incomeBeforeTaxRatio': 0.251438,
  'incomeTaxExpense': 28916000,
  'netIncome': 96223000,
  'netIncomeRatio': 0.193338,
  'eps': 2.28558,
  'epsdiluted': 2.28558,
  'weightedAverageShsOut': 42100000,
  'weightedAverageShsOutDil': 42100000,
  'link': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459019041652/0001564590-19-041652-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/1475922/000156459019041652/pri-10q_20190930.htm'}]

###  Calculates financial growth ,revenue, net income, EPS, and EBITDA growth

In [3]:
def growth(stock):
    #call the get_data2 function and store the results in a       
    #variable, data 2.
    data = get_data2(stock)
    
    #revenue growth
    rev_new = data[0]['revenue']
    rev_old = data[-1]['revenue']
    rev_change = 100*((rev_new-rev_old)/rev_old)
    #net income growth
    income_new = data[0]['netIncome']
    income_old = data[-1]['netIncome']
    income_change = 100*((income_new-income_old)/income_old)
    
    #EPS growth
    eps_new = data[0]['eps']
    eps_old = data[-1]['eps']
    eps_change = 100*((eps_new-eps_old)/eps_old)
    
    #EBITDA
    ebitda_new = data[0]['ebitda']
    ebitda_old = data[-1]['ebitda']
    ebitda_change = 100*((ebitda_new-ebitda_old)/ebitda_old)
    
    return (rev_change, income_change, eps_change, ebitda_change)

### Retrieving opreating performance metrics from different securities

In [4]:
stocks = ['PTON', 'MSFT', 'AAPL', 'AMD']
#store financials in a variable, data.
data = map(growth, stocks)
# populate DataFrame with data variable and create columns:
df1 = pd.DataFrame(data, columns=['Rev_Growth', 'Income_Growth', 'EPS_Growth', 'ebitda_Growth'], index=stocks)
data

df1.reset_index(inplace=True)
df1.rename(columns={'index': 'Symbol'}, inplace=True)
#display output
df1

  Symbol  Rev_Growth  Income_Growth  EPS_Growth  ebitda_Growth
0   PTON   62.341840    -224.548736 -221.291757    -298.492462
1   MSFT   12.400545      30.108635   32.856782      13.667608
2   AAPL    1.027483      -7.401724   -3.555244     -13.118910
3    AMD   55.524708    -100.000000 -100.000000     -55.450237

In [5]:
def dcf(stock):
    data = requests.get(f"https://financialmodelingprep.com/api/v3/discounted-cash-flow/{stock}?apikey={api_key}")
    data = data.json()
    dcf = data[0]['dcf']
    current_price = data[0]['Stock Price']
    return (dcf, current_price)

In [6]:
stocks = ['PTON', 'MSFT', 'AAPL', 'AMD']
data = map(dcf, stocks)
df2 = pd.DataFrame(data, columns=['dcf', 'current price'], index=stocks)
df2.reset_index(inplace=True)
df2.rename(columns={'index': 'symbol'}, inplace=True)
#Create a column that indicates under or over-valued
df2['value'] = df2.apply(lambda x: 'Under-valued' if x['dcf']>x['current price'] else 'Over-valued',axis=1)
#display results
df2

  symbol         dcf  current price         value
0   PTON  107.176533         102.49  Under-valued
1   MSFT  216.227018         214.46  Under-valued
2   AAPL  121.558846         119.39  Under-valued
3    AMD   84.668929          83.36  Under-valued

In [7]:
# Join industry peers
df = (
    pd.concat([df1,df2 ], axis='columns', join='inner').dropna()
)
df.head()

,Symbol,Rev_Growth,Income_Growth,EPS_Growth,ebitda_Growth,symbol,dcf,current price,value
0,PTON,62.341840,-224.548736,-221.291757,-298.492462,PTON,107.176533,102.49,Under-valued
1,MSFT,12.400545,30.108635,32.856782,13.667608,MSFT,216.227018,214.46,Under-valued
2,AAPL,1.027483,-7.401724,-3.555244,-13.118910,AAPL,121.558846,119.39,Under-valued
3,AMD,55.524708,-100.000000,-100.000000,-55.450237,AMD,84.668929,83.36,Under-valued